import { readdir } from "node:fs/promises";
import { join, relative, sep } from "node:path";

const upstreamRoot =
  Bun.env.GRAPHQL_JS_SRC ??
  "/var/folders/9j/q9tzjl0d7h91ks36p16m6_300000gn/T/opencode/graphql-js/src";
const localRoot = join(process.cwd(), "src", "alembic-graphql");
const outputPath = join(process.cwd(), "docs", "GRAPHQL_CORPUS_PARITY.md");

const explicitMappings = new Map<string, string>([
  [
    "utilities/__tests__/introspectionFromSchema-test.ts",
    "utilities/introspection-from-schema.test.ts",
  ],
  ["execution/__tests__/subscribe-test.ts", "execution/subscribe.test.ts"],
  ["error/__tests__/GraphQLError-test.ts", "error/graphql-error.test.ts"],
]);

async function collectFiles(root: string, predicate: (path: string) => boolean) {
  const files: Array<string> = [];

  async function walk(dir: string) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(path);
      } else if (entry.isFile() && predicate(path)) {
        files.push(toPosix(relative(root, path)));
      }
    }
  }

  await walk(root);
  return files.sort();
}

function toPosix(path: string) {
  return path.split(sep).join("/");
}

function kebabCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}

function canonicalUpstream(path: string) {
  const segments = path.split("/");
  const file = segments.pop();
  if (file === undefined) return path;
  const localFile = kebabCase(file).replace(/-test\.ts$/, ".test.ts");
  return [...segments, localFile].join("/");
}

function statusSquare(status: Status) {
  switch (status) {
    case "present":
      return "<span title=\"present\" style=\"color:#16a34a\">■</span>";
    case "mapped":
      return "<span title=\"mapped equivalent\" style=\"color:#2563eb\">■</span>";
    case "missing":
      return "<span title=\"missing\" style=\"color:#dc2626\">■</span>";
  }
}

type Status = "present" | "mapped" | "missing";

interface CorpusRow {
  readonly upstream: string;
  readonly local: string | undefined;
  readonly status: Status;
}

const upstreamFiles = await collectFiles(upstreamRoot, (path) => path.endsWith("-test.ts"));
const localFiles = await collectFiles(localRoot, (path) => path.endsWith(".test.ts"));
const localSet = new Set(localFiles);

const rows: Array<CorpusRow> = upstreamFiles.map((upstream) => {
  const mapped = explicitMappings.get(upstream);
  if (mapped !== undefined) {
    return {
      upstream,
      local: mapped,
      status: localSet.has(mapped) ? "mapped" : "missing",
    };
  }

  const canonical = canonicalUpstream(upstream);
  return {
    upstream,
    local: canonical,
    status: localSet.has(canonical) ? "present" : "missing",
  };
});

const present = rows.filter((row) => row.status === "present").length;
const mapped = rows.filter((row) => row.status === "mapped").length;
const missing = rows.filter((row) => row.status === "missing").length;
const covered = present + mapped;
const coverage = rows.length === 0 ? 0 : (covered / rows.length) * 100;
const gridRows: Array<string> = [];
for (let index = 0; index < rows.length; index += 39) {
  gridRows.push(rows.slice(index, index + 39).map((row) => statusSquare(row.status)).join(""));
}

const byDirectory = new Map<string, Array<CorpusRow>>();
for (const row of rows) {
  const testIndex = row.upstream.indexOf("/__tests__/");
  const directory = testIndex === -1
    ? row.upstream.slice(0, row.upstream.lastIndexOf("/")) || "."
    : row.upstream.slice(0, testIndex) || ".";
  const existing = byDirectory.get(directory);
  if (existing === undefined) {
    byDirectory.set(directory, [row]);
  } else {
    existing.push(row);
  }
}

const lines = [
  "# GraphQL.js Corpus Parity",
  "",
  "Generated by `bun scripts/graphql-corpus-dashboard.ts`.",
  "",
  `Upstream source: \`${upstreamRoot}\``,
  "",
  `Coverage: ${covered}/${rows.length} (${coverage.toFixed(1)}%)`,
  "",
  `Legend: ${statusSquare("present")} present ${statusSquare("mapped")} mapped equivalent ${statusSquare("missing")} missing`,
  "",
  "<p>",
  gridRows.join("<br />\n"),
  "</p>",
  "",
  "| Status | Count |",
  "| --- | ---: |",
  `| Present | ${present} |`,
  `| Mapped equivalent | ${mapped} |`,
  `| Missing | ${missing} |`,
  "",
];

for (const [directory, directoryRows] of [...byDirectory.entries()].sort()) {
  lines.push(`## ${directory}`, "");
  lines.push("| | Upstream | Local |", "| --- | --- | --- |");
  for (const row of directoryRows) {
    lines.push(
      `| ${statusSquare(row.status)} | \`${row.upstream}\` | ${row.local === undefined ? "" : `\`${row.local}\``} |`,
    );
  }
  lines.push("");
}

await Bun.write(outputPath, `${lines.join("\n")}\n`);
console.log(`Wrote ${outputPath}`);
console.log(`Coverage: ${covered}/${rows.length} (${coverage.toFixed(1)}%)`);
if (missing > 0) {
  console.log(`Missing: ${missing}`);
}
